name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy to [dev|prod].'
        default: dev
        required: true
  push:
    branches:
    - main
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: npm install

        - name: Build for development
          if: ${{ github.event.inputs.environment == 'dev' || !github.event.inputs.environment }}
          run:
            npm run build

        - name: Build for production
          if: github.event.inputs.environment == 'prod'
          run:
            npm run build

        - name: Deploy to dev
          if: ${{ github.event.inputs.environment == 'dev' || !github.event.inputs.environment }}
          uses: reggionick/s3-deploy@v3
          with:
            folder: public
            bucket: ${{ secrets.S3_DEV_BUCKET }}
            bucket-region: ${{ secrets.S3_DEV_BUCKET_REGION }}
            invalidation: /
            delete-removed: false
            no-cache: true
            private: true

        - name: Deploy to prod
          if: github.event.inputs.environment == 'prod'
          uses: reggionick/s3-deploy@v3
          with:
            folder: public
            bucket: ${{ secrets.S3_PROD_BUCKET }}
            bucket-region: ${{ secrets.S3_PROD_BUCKET_REGION }}
            invalidation: /
            delete-removed: false
            no-cache: true
            private: true
